import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";

export default function MeliTemplate({ children }: any) {
  const [query, setQuery] = useState("");

  const router = useRouter();

  const handleSearch = () => router.push(`/items?search=${query}`);

  return (
    <div>
      <Head>
        <title>Mini meli</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <input
            value={query}
            placeholder="search"
            onChange={(e) => setQuery(e.currentTarget?.value || "")}
          />
          <button onClick={handleSearch} disabled={query.length <= 0}>
            Search
          </button>
        </div>
        <div>{children}</div>
      </main>
    </div>
  );
}
